version: "3.6"

services:
  filebeat:
    build: filebeat/
    restart: always
    volumes:
      - ./pcap:/zeek_logs
    depends_on: 
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
    #  - discovery.seed_hosts=elasticsearch
      - discovery.type=single-node
      - node.name=elasticsearch
    #  - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - xpack.security.enrollment.enabled=false
      - xpack.security.enabled=false

    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    # forces other containers to wait until the process has started, rather than the container coming up
    # https://github.com/elastic/examples/blob/master/Miscellaneous/docker/full_stack_example/docker-compose-linux.yml#L42
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    restart: always
    depends_on: 
      - elasticsearch
    ports:
      - 5601:5601


volumes:
  esdata:
    name: zeek-sys-elk-esdata